<?php
	namespace View;
	use \Core\Core;
	use \Core\TwigCore;

	class View
	{

		private $filePath = "";
		private static $instance = null;

		/*
		 * Factorize loads the given parameter to a new View instance
		 * @params $filePath of the view template
		 * @returns the instance generated by factorize
		 */
		public static function factorize($file)
		{
			self::$instance = new View;
			self::$instance->setPath($file);
			return self::$instance;
		}

		/*
		 * SetPath is a function to point the template to the correct filepath
		 * @params file location relative to app/views
		 * @returns instance of the view component
		 */
		public function setPath($filePath) 
		{
			$this->filePath = $filePath;
			return $this;
		}

		/*
		 * Load will load the given filepath to the browser. it will not 'echo' the file rather, it'll return it
		 * @params $parms an array of variables needed to load the function 
		 * @returns a rendered html file
		 */
		public function load($parms = array())
		{
			return TwigCore::$twig->render($this->filePath, $parms);
		}
	}